baseURL = "https://sudorook.gitlab.io/capsule-demo"
languageCode = "en-us"
title = "Capsule Demo"
description = "Demonstration of features available in Capsule theme for Hugo."
canonifyURLs = true

theme = "capsule"
editor = "vim"
SectionPagesMenu = "main"
enableRobotsTXT = true
enableGitInfo = true
pygmentsstyle = "tango"
PygmentsCodeFences = true
DefaultContentLanguage = "no"
[author]
  name = "sudorook"
  email = "daemon@nullcodon.com"

[social]
  github = "sudorook"
  gitlab = "sudorook"

[params]
  repo = "https://gitlab.com/sudorook/capsule-demo"
  share = true
  searchURL = "https://duckduckgo.com"
  related = "all"

[languages]

  [languages.no]
  languageName = "Norsk"
  weight = 10
  contentDir = "content/no"
  
  [languages.en]
  languageName = "English"
  weight = 1
  contentDir = "content/en"

  [languages.fr]
  languageName = "Français"
  weight = 2
  contentDir = "content/fr"

  [languages.es]
  languageName = "Spanish"
  weight = 3
  contentDir = "content/es"